//go:build ignore

// constgen parses pkcs11t.h and generates Go constants and error strings.
//
// Usage:
//
//	go run ./cmd/constgen
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

func main() {
	f, err := os.Open("pkcs11t.h")
	if err != nil {
		fmt.Fprintf(os.Stderr, "open pkcs11t.h: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	var (
		consts     bytes.Buffer
		errs       bytes.Buffer
		comment    bytes.Buffer
		lastPrefix string
		constCount int
		errorCount int
	)

	consts.WriteString("// Code generated by \"go run ./cmd/constgen\"; DO NOT EDIT.\n\n")
	consts.WriteString("//go:build linux\n\n")
	consts.WriteString("package pkcs11\n\nconst (\n")

	errs.WriteString("// Code generated by \"go run ./cmd/constgen\"; DO NOT EDIT.\n\n")
	errs.WriteString("//go:build linux\n\n")
	errs.WriteString("package pkcs11\n\n")
	errs.WriteString("// strerror maps CKR_* return values to their string names.\n")
	errs.WriteString("var strerror = map[uint]string{\n")

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Accumulate block comments.
		if strings.HasPrefix(trimmed, "/*") && !strings.Contains(trimmed, "*/") {
			comment.Reset()
			comment.WriteString("// " + strings.TrimPrefix(trimmed, "/* ") + "\n")
			continue
		}
		if strings.HasPrefix(trimmed, "*") && !strings.HasPrefix(trimmed, "*/") {
			comment.WriteString("// " + strings.TrimPrefix(trimmed, "* ") + "\n")
			continue
		}
		if strings.HasPrefix(trimmed, "*/") {
			continue
		}

		if !strings.HasPrefix(trimmed, "#define") {
			continue
		}

		fields := strings.Fields(trimmed)
		if len(fields) < 3 {
			continue
		}

		name := fields[1]
		if len(name) < 3 || !strings.HasPrefix(name, "CK") {
			continue
		}

		// Skip non-constant macros.
		if name == "CK_PTR" || name == "CK_DISABLE_TRUE_FALSE" {
			continue
		}

		value := strings.Join(fields[2:], " ")
		// Strip inline comments.
		if idx := strings.Index(value, "/*"); idx >= 0 {
			inlineComment := strings.TrimSpace(value[idx:])
			inlineComment = strings.TrimPrefix(inlineComment, "/* ")
			inlineComment = strings.TrimSuffix(inlineComment, " */")
			inlineComment = strings.TrimSuffix(inlineComment, "*/")
			value = strings.TrimSpace(value[:idx])
			if inlineComment != "" {
				comment.WriteString("// " + inlineComment + "\n")
			}
		}

		// Convert C bitwise-not to Go before stripping parens.
		if strings.Contains(value, "~0") {
			value = "^uint(0)"
		}

		// Strip UL suffix from hex constants.
		value = strings.ReplaceAll(value, "UL)", ")")
		value = strings.ReplaceAll(value, "UL|", "|")
		value = strings.TrimSuffix(value, "UL")

		// Special cases.
		switch name {
		case "CK_TRUE":
			continue
		case "CK_FALSE":
			continue
		case "FALSE", "TRUE":
			continue
		}

		// Skip the ^uint(0) value before stripping parens.
		if value != "^uint(0)" {
			// Replace C-style casts and operators.
			value = strings.ReplaceAll(value, "(", "")
			value = strings.ReplaceAll(value, ")", "")
		}
		value = strings.ReplaceAll(value, "|", " | ")

		// Insert blank line on prefix change.
		if len(name) >= 3 {
			prefix := name[:3]
			if prefix != lastPrefix && lastPrefix != "" {
				consts.WriteString("\n")
			}
			lastPrefix = prefix
		}

		// Write accumulated comments.
		if comment.Len() > 0 {
			consts.WriteString(comment.String())
			comment.Reset()
		}

		consts.WriteString(fmt.Sprintf("\t%s = %s\n", name, value))
		constCount++

		// Also add CKR_* to error string map.
		if strings.HasPrefix(name, "CKR_") {
			errs.WriteString(fmt.Sprintf("\t%s: %q,\n", name, name))
			errorCount++
		}
	}

	consts.WriteString(")\n")
	errs.WriteString("}\n")

	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "scanning pkcs11t.h: %v\n", err)
		os.Exit(1)
	}

	// Format and write zconst.go.
	constFormatted, err := format.Source(consts.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "formatting zconst.go: %v\n%s\n", err, consts.String())
		os.Exit(1)
	}
	if err := os.WriteFile("zconst.go", constFormatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "writing zconst.go: %v\n", err)
		os.Exit(1)
	}

	// Format and write zerror_strings.go.
	errFormatted, err := format.Source(errs.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "formatting zerror_strings.go: %v\n%s\n", err, errs.String())
		os.Exit(1)
	}
	if err := os.WriteFile("zerror_strings.go", errFormatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "writing zerror_strings.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %d constants in zconst.go\n", constCount)
	fmt.Printf("Generated %d error strings in zerror_strings.go\n", errorCount)
}
